#
# System configuration file for cloud-tools
#

#
# instances and tasks sections, are just placeholders. They are not used by the code.
#
:instances:
  - !ruby/struct:Instance
    name: medium
    type: m1.medium
    price: .16

  # pvm
  - !ruby/struct:Instance
    name: mlarge
    type: m1.large
    price: .32

  # hvm
  - !ruby/struct:Instance
    name: mlarge-hvm
    type: c3.large # m3.large => 2 ECU, 7.5 RAM
    price: .105

  # pvm
  - !ruby/struct:Instance
    name: xlarge
    type: m2.xlarge
    price: .5

  # hvm
  - !ruby/struct:Instance
    name: xlarge-hvm
    type: r3.2xlarge
    price: .7

#
# Things like AMI's, ebs, snapshots... are region dependent
#
:regions:
  - &us-east !ruby/struct:Region
    name: us-east-1
    ami: ami-439df12a

  - &sa-east !ruby/struct:Region
    name: us-west-2
    #ami: ami-01575c31 # new account
    ami: ami-6f47685f # old-account
    #ami-e6a832d6

#
# We can have multiple credentials !
#
:credentials:
  # qa user - limited
  - &qa !ruby/struct:Credentials
    name: qa
    id: # go and get one !
    secret: # go and get one !

  # otheruser - admin
  - &david !ruby/struct:Credentials
    name: otheruser
    id: # go and get one !
    secret: # go and get one !

#
# masternode related settings
#
:masternode:
  :host: aws-logs.debian.net
  :ssh-user: user
  :work-dir: /home/user/cloud-scripts
  :ruby-interpreter: ruby2.1

#
# Default settings to use if not overriden but commandline parameters
#
:defaults:
  :region: *sa-east
  :credentials: *qa
  :tags:
    Team: Debian-QA
#  :securitygroups:
#    - Debian-QA
#    - no-network-access
#  :vpc-subnet-id: subnet-f0b10995
#  :vpc-securitygroups-ids:
#    - sg-97b7f8f2
